### ISSUE TITLE
Compile hypre by Mingw64

### ISSUE THREAD

**Issue by rockydut** [hypre-space/hypre#175]
Dear all:
When I compile hypre by mingw in msys2, it works well if dont't choose the HYPRE_USING_OPENMP.
When I set the HYPRE_USING_OPENMP on, it compiles error in mingw.
Errors occur in file "_hypre_struct_mv.h" as show below.

Hypre\hypre-master\src\struct_mv\_hypre_struct_mv.h:2497:19: warning: implicit declaration of function '__pragma'; did you mean '_Pragma'? [-Wimplicit-function-declaration]
 2497 | #define Pragma(x) __pragma(HYPRE_XSTR(x))
      |                   ^~~~~~~~

Hypre\hypre-master\src\struct_mv\_hypre_struct_mv.h:2577:4: error: expected ';' before 'for'
 2577 |    for (hypre__block = 0; hypre__block < hypre__num_blocks; hypre__block++)   \

Hypre\hypre-master\src\struct_mv\_hypre_struct_mv.h:2544:4: error: expected ';' before 'for'
 2544 |    for (hypre__block = 0; hypre__block < hypre__num_blocks; hypre__block++)   \

**Comment by liruipeng** [comment]
@rockydut I assume this is in MS-Windows. What compiler do you use? `__pragma` is the MS __pragma keyword see https://docs.microsoft.com/en-us/cpp/preprocessor/pragma-directives-and-the-pragma-keyword?view=vs-2019. In Linux, `_Pragma` is used.

**Comment by gkarpa** [comment]
@rockydut @liruipeng I had the exact same problem as well when trying to build hypre in Windows with openmp enabled using gcc and msys2, and I found a way to get around it. There are three files that have the exact same issue:
`src/struct_ls/red_black_gs.h
src/struct_mv/boxloop.h
src/struct_mv/_hypre_struct_mv.h (lines 1743-1747)`

This seems to happen because in order to `#define Pragma(x)` the code is checking if WIN32 is defined and uses __pragma instead of _Pragma. __pragma() though is MSVC's preprocessor operator as @liruipeng correctly noted. However, checking if WIN32 is defined is not enough since we could indeed be in Windows but not using MSVC as our compiler.

My solution was to modify the 3 `#ifdef WIN32` statements to `#if defined(WIN32) && defined(_MSC_VER)` in order to check that we are indeed building with an MSVC compiler, and only then the __pragma() call should be used. _MSC_VER is "an integer literal that encodes the major and minor number elements of Microsoft's compiler's version number" so it should not be defined when building with e.g. gcc, which will cause the code to define using _Pragma instead of __pragma. Looking forward to your feedback.

Regards,
George

**Comment by rfalgout** [comment]
Thanks @rockydut and @gkarpa for pointing out this issue.  It looks like `_MSC_VER` is the way to go here.  I'm not sure we should be using `WIN32` anywhere in the code.

**Comment by liruipeng** [comment]
@rfalgout This fix makes sense to me. Thanks!

**Comment by liruipeng** [comment]
This issue was not resolved and should not have been closed, which is related to #219.

**Comment by rockydut** [comment]
I use Msys with mingw in Window. I think it should identify the mingw copiler as pointed by @gkarpa .

**Comment by liruipeng** [comment]
The fix has been merged. Thanks!
