### ISSUE TITLE
Solve Poisson Equation with Pure Neumann Boundary Conditions using MG sovlers

### ISSUE THREAD

**Issue by suguanting** [hypre-space/hypre#177]
Dear HYPRE developers,

I am trying to solve a Poisson Equation with Pure Neumann Boundary Conditions using MG sovlers (e.g., SMG, PFMG...) in the struct interface.  As [widely discussed](https://scicomp.stackexchange.com/questions/21612/poisson-equation-finite-difference-with-pure-neumann-boundary-conditions), such Neumann problem has multiple solutions that deviate from each other by a constant. Therefore, some treatment to "anchor" the solution is necessary.

I have tried setting the corner of the solution field to 0 by embedding x(0,0,0)=0 into the matrix A and rhs vector b instead of the original discretized equation. Based on my results, this treatment works well for 2-D problems, but not for 3-D problems (error accumulated in the corner where the anchor is imposed)

So could you give me some advice on approaches to "anchor" the solution that better suits HYPRE? Other than imposing the anchor at the corner, I am also aware that one can fix the mean of the solution to zero. But I cannot simply do that after HYPRE solver produces a solution as the solver won't even converge without an anchor. It will sometimes reach a solution with values of ~10^100 that eventually caused divergence.

Thanks in advance for any help,

Guanting

ps. the compatibility condition is satisfied (the integration of the rhs value is zero) in the problem I am working with.

**Comment by rfalgout** [comment]
Hi @suguanting .  Normally we just recommend projecting the null space (a constant vector in this case) out of the solution vector returned from hypre.  If you are using multigrid to precondition CG, then you just need to start with an initial guess of zero and CG will automatically converge to the solution orthogonal to the null space (so, you don't need to project anything).

I didn't really follow how you imposed the x(0,0,0) = 0 condition in the matrix.  Can you elaborate?  Hope this helps.  Thanks!

**Comment by suguanting** [comment]
Thanks for helping out @rfalgout !

> I didn't really follow how you imposed the x(0,0,0) = 0 condition in the matrix. Can you elaborate?

For point (0,0,0) (this is the FORTRAN form, which refers to point [0][0][0] as in C fashion), I set all related coefficients in Matrix A to be zero, except for the one that corresponds to offset (0,0,0) (i.e., the point itself). And the value of RHS vector b for this particular point is set also to zero. I hope this makes better clarification.

> Normally we just recommend projecting the null space (a constant vector in this case) out of the solution vector returned from hypre

Is there a function to do this every iteration within HYPRE solver or do you mean that I just substract a desirable constant after the solver converges? If it is the latter, then it may not work for the situation I have encountered, in which the HYPRE SMG solver will diverge with the solution close to a randmoly large constant. I think the SMG solver just "settled" on a random constant value and if the value is large, it caused exaggeration of machine error that eventually lead to divergence. This only happen when I called the solver multiple times within a flow solver of mine and curiously only when I build under "release" mode. I didn't further investigate why after I found out that I can get rid of this problem by adding the "numerical anchor".

> If you are using multigrid to precondition CG, then you just need to start with an initial guess of zero and CG will automatically converge to the solution orthogonal to the null space (so, you don't need to project anything).

This looks really promising and is definitely a more elegant approach compared with my "anchoring". So right now I am trying to switch to a PCG solver and have started with the one presented in ex3.c with my problem. However, the solver didn't converge. 
![image](https://user-images.githubusercontent.com/14161266/90188924-ddb80100-ddee-11ea-81f8-96b41afed984.png)

I noticed that the default solver in ex3.c uses a symmetric SMG as preconditioner and the matirx in my problem is not symmetric. Could it be the problem? I am uploading the code and some necessary data to prepare A and b for better reference, see attached.


[fortran code.txt](https://github.com/hypre-space/hypre/files/5071628/fortran.code.txt)
[FRHS.txt](https://github.com/hypre-space/hypre/files/5071599/FRHS.txt)
[FA1.txt](https://github.com/hypre-space/hypre/files/5071600/FA1.txt)
[FA2.txt](https://github.com/hypre-space/hypre/files/5071601/FA2.txt)
[FA3.txt](https://github.com/hypre-space/hypre/files/5071602/FA3.txt)
[FB1.txt](https://github.com/hypre-space/hypre/files/5071603/FB1.txt)
[FB2.txt](https://github.com/hypre-space/hypre/files/5071604/FB2.txt)
[FB3.txt](https://github.com/hypre-space/hypre/files/5071605/FB3.txt)


Thank you again for your help,

Guanting

**Comment by rfalgout** [comment]
Hi @suguanting .  Thanks for the clarification on x(0,0,0).  I would definitely suggest that you make this change in a symmetric way, so any equations that couple to x(0,0,0) should also be modified by zeroing out the coupling and appropriately updating it's right-hand-side (in this case, since you are setting the value of x(0,0,0) to zero, you don't need to actually change the rhs).

Why is your matrix not symmetric, other than the "anchor point" boundary condition?  Poisson with any type of boundary conditions can be discretized symmetrically.  You'll need this to use CG.  In addition, you will need to ensure that the multigrid cycle is also symmetric, i.e., use the same number of pre- and post-relaxations (note that you'll have to do more to get symmetry if you use PFMG, which is a more efficient solver than SMG for Poisson).

You only need to project out the null space at the end of the solve.  We don't have a routine that specifically does this, so you'll have to take care of it yourself.  If x is your solution, replace it with x - (x^T 1)/(x^T x) where '1' is a vector of all ones.

I don't think SMG should "diverge" as you say.  It sounds like the large constant is creeping in over the coarse of several solves.  If you project it out after each solve, I think you will be okay.  Let us know if you continue to have issues.

Thanks!

**Comment by suguanting** [comment]
Hi @rfalgout, these are really helpful, thanks! 

Based on your comments, I first came to realize that symmetry could be rather important when using HYPRE. Based on my current understanding, CG-type solvers only work for symmetric problems, and even though SMG and PFMG can deal with non-symmetric problems but achieving symmetry would greatly improve their performance, am I right?

> Why is your matrix not symmetric, other than the "anchor point" boundary condition? Poisson with any type of boundary conditions can be discretized symmetrically.

I used a non-uniform Cartesian grid and a center difference scheme. So for 1-D problems, the discretized equation looks like this:
![image](https://user-images.githubusercontent.com/14161266/90266891-4d79ca80-de87-11ea-9ded-dfca925e9482.png)
A1(i+1) do not equal to A3(i) by definition, therefore the matrix I used right now is not symmetric. Is there a way to discretize the Poisson equation symmetrically on a non-uniform Cartesian grid? I would be very interested given that symmetry play such important role. Could you kindly provide some reference or some hint on where I should look up?

> If x is your solution, replace it with x - (x^T 1)/(x^T x) where '1' is a vector of all ones.

I am sorry but I am confused about the actual expression that you are refering to. Are you suggesting that I do this:
![image](https://user-images.githubusercontent.com/14161266/90269499-4fde2380-de8b-11ea-995f-f9b3a283a2a5.png)

Thank you again for your help,

Guanting

**Comment by liruipeng** [comment]
> Hi @suguanting . Thanks for the clarification on x(0,0,0). I would definitely suggest that you make this change in a symmetric way, so any equations that couple to x(0,0,0) should also be modified by zeroing out the coupling and appropriately updating it's right-hand-side (in this case, since you are setting the value of x(0,0,0) to zero, you don't need to actually change the rhs).
> 
> Why is your matrix not symmetric, other than the "anchor point" boundary condition? Poisson with any type of boundary conditions can be discretized symmetrically. You'll need this to use CG. In addition, you will need to ensure that the multigrid cycle is also symmetric, i.e., use the same number of pre- and post-relaxations (note that you'll have to do more to get symmetry if you use PFMG, which is a more efficient solver than SMG for Poisson).
> 
> You only need to project out the null space at the end of the solve. We don't have a routine that specifically does this, so you'll have to take care of it yourself. If x is your solution, replace it with x - (x^T 1)/(x^T x) where '1' is a vector of all ones.
> 
> I don't think SMG should "diverge" as you say. It sounds like the large constant is creeping in over the coarse of several solves. If you project it out after each solve, I think you will be okay. Let us know if you continue to have issues.
> 
> Thanks!

@rfalgout You meant: `x - (x^T 1)/(1^T1) 1`, right? @suguanting

**Comment by rfalgout** [comment]
Hi @suguanting .  I messed up the whole projection.  Sorry about that.  It should be x - 1 (1^T x)/(1^T 1).  This will make the new x orthogonal to 1, that is, 1^T x_new = 0.  If you want to just get the same effect as what you were doing with anchoring, you could also replace x with x - x(0,0,0) 1.  This subtracts off the constant vector such that the x_new(0,0,0) = 0.

A finite element discretization would give you a symmetric matrix.  There should be an equivalent finite difference way to do this as well, even on a non-uniform mesh.  I don't recall exactly what it is, though.

If you want to stick with your current non-symmetric discretization, you can use GMRES instead of CG.

Hope this helps.  Sorry again for the confusion.

**Comment by suguanting** [comment]
Hi @rfalgout @liruipeng , thanks for the clarification!

Following your suggestion, I tried GMRES with SMG preconditioning and replaced the final output x with a new x whose overall sum of elements is zero (i.e. orthogonal to 1). The solver worked generally well and actually eliminated an error I had when embedding the numerical anchor as I had been doing. So some progress! 

The only issue is that I am getting a lot of "false convergence" error flags (as shown in the screen shot), which start popping out when the solver subroutine is called a second time within one simulation case.
![微信图片_20200815230432](https://user-images.githubusercontent.com/14161266/90315227-541e4580-df4c-11ea-8b91-1bab428a7c7c.png)

Note that for the first call where there is no error flag, the solver converges to residual A that is below the error tolerance I set (=10^-6) and equal to the final relative residual B. However, for the second call where I am starting to get error flag, this is no longer the case. After getting a residual C that is already smaller than 10^-6, the solver surprisingly continues and output a error flag. And for unknown reason, it decides to break out with residual D that is smaller than 10^-6. And more surprisingly, the final residual E does not equal to residual D.

So what are the possible reason for the GMRES solver to behave like this? I suspect I might have missed something in solver setup. Below is the code I used to set up the solver and the preconditioner. 

           ```

            ! Create an empty GMRES Struct solver
            CALL HYPRE_StructGMRESCreate(MPI_COMM_F, SOLVER_MG, IERR)

            ! Set some parameters
            CALL HYPRE_StructGMRESSetMaxIter(SOLVER_MG, 50, IERR)
            CALL HYPRE_StructGMRESSetTol(SOLVER_MG, CRITERIA, IERR)
            CALL HYPRE_StructGMRESSetPrintLevel(SOLVER_MG, 2, IERR)!/* PRINT EACH CG ITERATION */
            CALL HYPRE_StructGMRESSetLogging(SOLVER_MG, 1, IERR)

            ! Use symmetric SMG as preconditioner
            CALL HYPRE_StructSMGCreate(MPI_COMM_F, PRECOND_MG, IERR)
            CALL HYPRE_StructSMGSetMemoryUse(PRECOND_MG, 0, IERR)
            CALL HYPRE_StructSMGSetMaxIter(PRECOND_MG, 1, IERR)
            CALL HYPRE_StructSMGSetTol(PRECOND_MG, 0.0, IERR)
            CALL HYPRE_StructSMGSetZeroGuess(PRECOND_MG, IERR)
            CALL HYPRE_StructSMGSetNumPreRelax(PRECOND_MG, N_PRE_MG, IERR)
            CALL HYPRE_StructSMGSetNumPostRelax(PRECOND_MG, N_POST_MG, IERR)

            ! Setup and solve
            CALL HYPRE_StructGMRESSetPrecond(SOLVER_MG, 0, PRECOND_MG, IERR)
            CALL HYPRE_StructGMRESSetup(SOLVER_MG, A_MG, B_MG, X_MG, IERR)
            CALL HYPRE_StructGMRESSolve(SOLVER_MG, A_MG, B_MG, X_MG, IERR)

            ! Get some info on the run
            CALL HYPRE_StructGMRESGetNumIteratio(SOLVER_MG,NUM_ITERATIONS_MG,IERR)
            CALL HYPRE_StructGMRESGetFinalRelati(SOLVER_MG,FINAL_RES_NORM_MG,IERR)

            ! Free memory
            CALL HYPRE_StructSMGDestroy(PRECOND_MG,IERR)
            CALL HYPRE_StructGMRESDestroy(SOLVER_MG, IERR)

FYI, CRITERIA=10^-6, N_PRE_MG=N_POST_MG=1

Sorry that I am taking so much of your time and thank you again for your help! 

Guanting

**Comment by rfalgout** [comment]
Hi @suguanting .  False convergence sometimes happens in Krylov methods, though it's not that common when the method is converging quickly as in your case.  Basically, the residual in these methods is often computed indirectly, through some equivalent mathematical relation (for efficiency reasons).  The latter can "drift" from the actual value due to numerical roundoff (in exact arithmetic, everything is fine).  It looks like what happened in your case was that a third "false convergence" was detected, but hypre quit before reporting it because the actual residual increased in value (note that the 4.629 in the "Final L2" printout is larger than the 4.624 in the last reported "false convergence" line.

The big question is why this is happening.  Is the compatibility condition still being satisfied (you mentioned earlier that it was)?

Thanks!

**Comment by suguanting** [comment]
Hi @rfalgout , thanks for the explanation! 

I have checked the volume Integral of the RHS of the poisson equation in my problem. For the first iteration (with no error flag), the integral is ~10^-13 (~10^-17 relative to the max value of the RHS). For the second iteration (where error flags are shown), the  integral is ~10^-9 (~10^-14 relative to the max value of the RHS).

Could such error deteriorate the performance of the solver to such a large extent? 

Again, thanks for helping out!

Guanting

**Comment by rfalgout** [comment]
Hi @suguanting .  Residual drift is usually caused by ill-conditioning (of the preconditioned system).  In your case, I thought the preconditioner converged pretty quickly, which makes this somewhat puzzling.  I'm not sure if the volume integral values you give here are problematic, but having an inconsistent rhs is not something you want to have.  Can you adjust the rhs to make the volume integrals smaller to see if that helps?  Are you still using the anchor here?  If you run without GMRES, is the convergence fast or slow?  Are you implementing the anchor in a symmetric way with respect to the matrix couplings to and from x(0,0,0) (I realize that the rest of the matrix is not symmetric, but I would still recommend implementing the anchor this way)?  Have you tried any of this without the anchor?

Sorry for all the questions.

**Comment by suguanting** [comment]
Hi @rfalgout ! Thank you for the reply, I would be very happy to answer these questions to the best I could.

> Residual drift is usually caused by ill-conditioning (of the preconditioned system)

Is the ill-conditioning (of the preconditioned system) generally related to a ill-conditioned matrix A used in the problem? Without embedding the numerical anchor in the "x(0,0,0)=0" fashion, the matrix A I used is singular due to the pure Neumann conditions. Should I check the condition number of the matrix A used in the problem after embedding the numerical anchor? Is it pertinent to the ill-conditioning?

> Can you adjust the rhs to make the volume integrals smaller to see if that helps? 

I tried explicitly adjusting the rhs by subtracting the value of the integral divided by the volume of the computation domain. I found that the resulted integral after adjustment is still ~10^-9 and the behavior of the solver is basically unchanged. The integral's slight deviation from zero should be attributed to machine error when treating RHS of large value (~10^4) and machine error integrated over the volume (20 * 20 * 12 in the problem)

> Are you still using the anchor here?

Yes, but not in the "x(0,0,0)=0" fashion. When I am using gmres, the overall sum of x is adjusted to zero after the solver output the x.

> If you run without GMRES, is the convergence fast or slow?

If I change the solver back to SMG: without implementing the numerical anchor in the "x(0,0,0)=0" fashion, the first call of the solver will converge to less than 10^-6 after 5 iterations, but the second call of the solver won't converge even after 50 iterations; with the numerical anchor implemented in the "x(0,0,0)=0" fashion (the original "not symmetric" way), both call of the solver converge to less than 10^-6 after 5 iterations.

> Have you tried any of this without the anchor?

For SMG solver, implementing an anchor (in the "x(0,0,0)=0" fashion) seems to be the prerequisite of normal convergence. For GMRES, implementing the anchor by adjusting overall sum of x to zero after the solver output the x does not seem to affect the convergence of the solver significantly: the second call of the solver output "false convergence" with or without such anchor. 

However, one more thing that I haven't tried before is implementing an anchor in the "x(0,0,0)=0" fashion to the GMRES solver, and this time the solver converged well with no "false convergence" flags. So it seems that implementing an anchor in the "x(0,0,0)=0" fashion is the prerequisite of normal convergence also for GMRES solver.

One more question, how to output every iteration of the SMG solver. I have tried using this:

```
            CALL HYPRE_StructSMGSetPrintLevel(SOLVER_MG, 2, IERR)
            CALL HYPRE_StructSMGSetLogging(SOLVER_MG, 1, IERR)
```
,and changing the number I input in the `HYPRE_StructSMGSetPrintLevel`, but could not achieve the output.

Thank you for your time and help!

Guanting

**Comment by rfalgout** [comment]
Hi @suguanting .  The ill-conditioning comment is for the preconditioned system, not A.  You can get a sense of this by simply seeing how quickly the preconditioner converges.  It appears that SMG does not converge well for the second system.

It's still a bit puzzling to me that you can't get the integral of the rhs down to a smaller number, because this isn't a large problem.  Note that the large size of 10^4 is not necessarily an issue.  What can be an issue, though, are large variations in the rhs, especially if there are both positive and negative values.  Reordering the summation in the integral can greatly reduce roundoff issues, and maybe that is something to try.  Grouping values of similar sign and size and summing them into separate bins first before adding the bins is one technique that can help (for example, the bins can be large-positive, small-positive, large-negative, small-negative, or even further refined).

I am not so sure that adjusting the rhs differently will solve the problem, though.  It seems that SMG is struggling with roundoff issues related to the null space, but it may be difficult to uncover exactly why that's the case, especially since you have some nonsymmetry in the problem due to the variably-space grid (and SMG is designed for symmetric problems).

Using the x(0,0,0)=0 anchor appears to be your best bet for stabilizing everything.  Using GMRES may still be a good idea, because it should add some robustness.  I'm not sure if it is also giving you a speedup in solve time, because we haven't really talked about that.

Neither SMG nor PFMG have more detailed residual printing implemented.

Thanks for providing such detail in your posts!  Let us know if you have other questions or issues.

**Comment by suguanting** [comment]
Hi @rfalgout ,

Thank you for the advice on reducing the integral. As you expected, they are large variations in the rhs (max~+10^4, min~-10^4). I will definitely try the "separate bin" method to find out what is really going on later.

Like you said, my best bet is to embed an x(0,0,0)=0 anchor in the GMRES solver. And since it is at least working properly, I will go along with this approach for the time being. And yes, the GMRES solver is faster than a pure SMG solver, about 30%, based on a 2D problem.

Thank you for your help during these time, it solves my problem and really improves my understanding towards HYPRE! I just have some last questions:

Since SMG is designed for symmetric problems, is my understanding correct that SMG sovler may also work for asymmetric problems? It is just that its performance is not guaranteed (or more unpredictable)? And is it the same for the SMG preconditioner of GMRES solver?

> You can get a sense of this by simply seeing how quickly the preconditioner converges.

How can I output the convergence of the preconditioner? Is there a function for this?

Thank you again for your help,

Guanting

**Comment by rfalgout** [comment]
To see the convergence of the preconditioner, you just need to see how many iterations SMG takes to solve the problem to your tolerance.  You were taking more than 50 without the anchor, so that's not good convergence.  We don't have a function that returns convergence rate.

The SMG solver can work for non-symmetric problems, but may have trouble in highly non-symmetric situations.  Because you have a singular system, it may be that this combined with the non-symmetry is the reason for the unstable performance of SMG (when you don't have the anchor).  I would need to think this through more carefully.  In general, singular systems should not be a problem in my experience.

**Comment by suguanting** [comment]
Thank you for the clarification, which is really helpful!
