### ISSUE TITLE
Plot of example 3

### ISSUE THREAD

**Issue by Huq2090** [hypre-space/hypre#192]
I was wondering, why the plot of example 3 doesn't show zero value at all the boundaries, since in the code, boundary values are explicitly set to zero for all the boundaries? 
For reference, here is the command line input string: mpirun -np 16 ./ex3 -n 33 -solver 0 -vis

![image](https://user-images.githubusercontent.com/36095989/93383686-9d9ed080-f829-11ea-95db-4421c43f679a.png)

**Comment by rfalgout** [comment]
Hi @Huq2090 .  The boundaries in the picture are not the physical domain boundaries, they are the points right next to them (one mesh spacing away).  This example only computes the values inside the grid (the boundary conditions are incorporated into the right-hand-side), and the visualization is currently set up to only plot the computed values.  If you solve larger and larger problems, the minimum value in the figure should get closer and closer to zero.  Hope this helps!

**Comment by Huq2090** [comment]
Thank you. That make it clear. Is there anyway I can plot including boundary values?
Thank you once again.

**Comment by rfalgout** [comment]
Not without writing some code.

In the single processor case, it shouldn't be too bad.  I think you only need to modify the code in the `if (vis)` section near the bottom of `ex3.c`.  You need the `fprintf` line to also print zero boundary values and you will need to adjust the argument in `GLVis_PrintGlobalSquareMesh` to be `N*n + 1`.

In the parallel case, things get trickier because not all processors would print the same amount of data; some will have additional boundary values to print.

Maybe the easiest way to do this is to post-process the glvis files, namely, the `$mesh` and `$sol` files that are generated by the script `vis/glvis-ex3.sh` (near the bottom of the script).  You would need to write some code to modify both of these files to include the boundary mesh points and their zero values.
