### ISSUE TITLE
BoomerAMG convergence depends on the number of threads used...

### ISSUE THREAD

**Issue by andraspap** [hypre-space/hypre#209]
We are using HYPRE's AMG solver and the convergence rate varies by thread counts. The input matrix and the right hand side isn't changing. I wonder if this is normal? 
This data is from running on a single PC with 6 cores.
[
<img width="673" alt="ThreadCountDependence" src="https://user-images.githubusercontent.com/1832473/94492159-a68f8a80-01b7-11eb-9a93-46faf90183f8.PNG">
](url)

**Comment by ulrikeyang** [comment]
Yes, this is to be expected, since the default smoother (hybrid L1_Gauss-Seidel) depends on the number of threads. Only for 1 thread the smoother would be Gauss-Seidel, but it becomes a hybrid scheme when you increase the number of threads and often leads to slightly worse convergence. You could change the smoother by setting it to a Jacobi (relaxtype 0 or 18 for L1-Jacobi) or polynomial smoother (relaxtype 16) and you won't have this issue. Jacobi  (0) should generally be used with a relaxation weight.

**Comment by andraspap** [comment]
Thank you very much for your response, understanding this helps us a lot.
