### ISSUE TITLE
Runtest options -rtol and -atol

### ISSUE THREAD

**Issue by rfalgout** [hypre-space/hypre#272]
Hi @oseikuffuor1 .  It looks like the `-rtol` and `-atol` options cannot be used individually, only together.  I can't remember if we already knew this, because we use it correctly in the main regression test scripts.  Let me know if I am reading this right.  Thanks!

**Comment by oseikuffuor1** [comment]
@rfalgout, they are usually used together, but are not required. It makes sense to specify at least one of them, otherwise the tests will invariably fail since our convergence tolerances are > 0.0. The runtest.sh script, which uses these options, sets a default value (which cannot be attained) to the option that is not set, so the PASS/FAIL check  only relies on the value of the option that is set. The default for atol is -1.0 and the default for rtol is 0.0, since it is also used to test for changes in integer output such as iteration counts.

**Comment by rfalgout** [comment]
Hi @oseikuffuor1 .  If the intention is to be able to use rtol/atol separately, then we need to fix the current implementation (which I am happy to do).  The problem is that RTOL and ATOL are sometimes not defined, so when you try to set them separately (atol, in particular), they get mixed up.  To see this, I added an echo line to the `runtest.sh` script in function `ExecuteTest` to see their values.  Here is what happens:

    > runtest.sh TEST_struct/emptyproc.sh
    rtol=, atol=
    > runtest.sh -rtol 0.1 TEST_struct/emptyproc.sh
    rtol=0.1, atol=
    > runtest.sh -atol 0.2 TEST_struct/emptyproc.sh
    rtol=0.2, atol=
    > runtest.sh -rtol 0.1 -atol 0.2 TEST_struct/emptyproc.sh
    rtol=0.1, atol=0.2

Currently, we either don't use either of them or we use both, so all is good in our regression testing.

**Comment by oseikuffuor1** [comment]
Hi @rfalgout, in my earlier comment, I actually meant the runcheck.sh script, not the runtest.sh script is what does the testing. I believe your test is only printing the local values of rtol and atol, but what is actually used in the check is defined in runcheck.sh. If either rtol or atol is passed in through the runtest.sh script, then it will use that. Otherwise, the default value is used. Also, my earlier comment about needing one of them is not entirely true. If neither is provided, then an rtol value of 0.0 is used to do the check, which means values compared from the saved and out files must be identical. There is an echo line commented out in the runcheck.sh script which should print out what is actually used in the test.

**Comment by oseikuffuor1** [comment]
Sorry if my use of testing and checking is confusing. The runcheck.sh script does the PASS/FAIL checking and so rtol and atol are passed down to this script. If only one is provided, it would be used as rtol (due to the syntax for invoking the script: ./runcheck outfield savedfile rtol atol). If neither is provided, then a default value of 0. is used for rtol. atol is used as a secondary check if rtol is not satisfied and atol is provided.

**Comment by rfalgout** [comment]
Hi @oseikuffuor1 .  It looks like you see my point that if only atol is passed, then it is used for rtol instead.  Is that the expected behavior, or should atol never be used by itself?

**Comment by oseikuffuor1** [comment]
Hi @rfalgout, yes I believe the intent was to use atol only if provided as additional option. I don't have strong feelings about this decision, so if an alternate strategy makes more sense to you, I'd be fine with that. So to answer your question, yes to use atol, both rtol and atol have to be passed together. Otherwise only rtol is used.

**Comment by rfalgout** [comment]
Okay.  If that's the way it's intended to be used, then all is good.  No need to change a thing.  Thanks again!
