### ISSUE TITLE
Discrepancy of max norm between distributed ranks

### ISSUE THREAD

**Issue by AerysL** [hypre-space/hypre#390]
It appears to me that in `par_relax_more.c` that the returned `max_norm` may not be consistent between ranks in certain edge cases. Particulaily if the evaluation of the if statement on line 93 (https://github.com/hypre-space/hypre/blob/1d9411c7ab67600f1aa73febfff6aa658ab08ea2/src/parcsr_ls/par_relax_more.c#L93) is evaluated differently on each rank. While `max_norm` is reduced such that it is the same on all ranks on line 89 and 90 (https://github.com/hypre-space/hypre/blob/1d9411c7ab67600f1aa73febfff6aa658ab08ea2/src/parcsr_ls/par_relax_more.c#L89), the `pos_diag` and `neg_diag` variables are only ever local. If the input matrix has a significantly different spectrum rank to rank (e.g. strictly negative diagonal on one rank and not on another), the if statement could evaluate differently between ranks. 

I would expect that `max_eig` is used in such a way where one would want it to be consistent between ranks. Is this a bug?

Mentioning  @rfalgout @ulrikeyang  at @liruipeng 's request

**Comment by liruipeng** [comment]
I guess this is for negative definite matrices. @AerysL made good points on the local and global.
The idea I guess was to check if there is no positive diagonal and but negative ones (`neg_diag > 0`), so we can guess (?) it is a negative definite matrix. So we return the estimate of smallest (negative) eigenvalue  as `-l1_norm`. Global numbers of `pos_diag` and `neg_diag` appear to be more appropriate to me, if I understand it correctly. Any thoughts @rfalgout @ulrikeyang? Thanks!

**Comment by liruipeng** [comment]
@rfalgout @ulrikeyang Any thoughts on this issue? Thanks!

**Comment by rfalgout** [comment]
It is okay to check the sign of the diagonal locally for matrices that are symmetric and definite (either positive or negative definite), and it appears that is what the routine is assuming.  It's probably almost always okay in the semi-definite cases as well.  Since this is basically equivalent to using Gershgorin estimates, we could rewrite it to explicitly do that.  Both the lower and upper disk bounds would have to be computed and all-reduced, but the changes would be relatively minor and would makes sense for all matrices.  Whether the effectiveness of the Chebyshev smoother is achieved with these estimates is another matter.  I am on the fence about changing anything here.
