### ISSUE TITLE
Regression in 2.21 with nodal coarsening? Failing test from PETSc

### ISSUE THREAD

**Issue by stefanozampini** [hypre-space/hypre#393]
We recently tried upgrading to 2.21 in PETSc (see https://gitlab.com/petsc/petsc/-/merge_requests/4058), and we got a failure in our test suite, see here https://gitlab.com/petsc/petsc/-/jobs/1311438082#L3940. This test solves 2D elasticity with checkerboard coefficients, here is the source code and the options used for the test https://gitlab.com/petsc/petsc/-/blob/main/src/ksp/ksp/tutorials/ex49.c#L1324.
We are using nodal coarsening 6 and vec_interp_variant 3.
Reporting this since you mention in the changelog `Fixed a bug in the strength matrix generation for nodal AMG`

**Comment by ulrikeyang** [comment]
Is the problem that it stopped converging? Yes, this change caused some changes in convergence, in some cases better and in some worse.

From: Stefano Zampini ***@***.***>
Sent: Friday, June 4, 2021 10:23 AM
To: hypre-space/hypre ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hypre-space/hypre] Regression in 2.21 with nodal coarsening? Failing test from PETSc (#393)


We recently tried upgrading to 2.21 in PETSc (see https://gitlab.com/petsc/petsc/-/merge_requests/4058<https://urldefense.us/v3/__https:/gitlab.com/petsc/petsc/-/merge_requests/4058__;!!G2kpM7uM-TzIFchu!ns_YH0W2OIAcuLhgXh7nmzAND4DtwO7qGTsxaBCF13lqLLicpVXwbigpOmjBodof$>), and we got a failure in our test suite, see here https://gitlab.com/petsc/petsc/-/jobs/1311438082#L3940<https://urldefense.us/v3/__https:/gitlab.com/petsc/petsc/-/jobs/1311438082*L3940__;Iw!!G2kpM7uM-TzIFchu!ns_YH0W2OIAcuLhgXh7nmzAND4DtwO7qGTsxaBCF13lqLLicpVXwbigpOhVBT63B$>. This test solves 2D elasticity with checkerboard coefficients, here is the source code and the options used for the test https://gitlab.com/petsc/petsc/-/blob/main/src/ksp/ksp/tutorials/ex49.c#L1324<https://urldefense.us/v3/__https:/gitlab.com/petsc/petsc/-/blob/main/src/ksp/ksp/tutorials/ex49.c*L1324__;Iw!!G2kpM7uM-TzIFchu!ns_YH0W2OIAcuLhgXh7nmzAND4DtwO7qGTsxaBCF13lqLLicpVXwbigpOi7N6N6l$>.
We are using nodal coarsening 6 and vec_interp_variant 3.
Reporting this since you mention in the changelog Fixed a bug in the strength matrix generation for nodal AMG

**Comment by stefanozampini** [comment]
It is still converging, but with many more iterations. If you say it is expected, we can whitelist this error.

**Comment by ulrikeyang** [comment]
Yes, it unfortunately affects certain interpolation operators more negatively than others. Do you know which interpolation you are using for this example?

**Comment by stefanozampini** [comment]
You mean the one selected with `HYPRE_BoomerAMGSetInterpVecVariant`? for this, we use 3

**Comment by prj-** [comment]
I've updated our output file, but going from 8 to 18 iterations seems rather brutal. We'll wait for your confirmation or further comments. I guess this should impact elasticity examples from MFEM as well?

**Comment by ulrikeyang** [comment]
It’s brutal for this example, but it has improved things for other examples. We would have to look at the individual cases.
The question is again which interpolation operator was used. It seemed to be better with distance-two interpolation operators vs distance-one operators.

**Comment by prj-** [comment]
Switching from 2.21.0 to 1d9411c changed yet again the number of iterates (from 18 to 15). With the additional parameter `-elas_pc_hypre_boomeramg_interp_type ext+i`, we are back at 9 iterations, so I think it's OK.
