### ISSUE TITLE
Potential problem with par_vector.c? Running with IJ interface requires indexing starting at zero

### ISSUE THREAD

**Issue by desjardi** [hypre-space/hypre#396]
I've recently updated to the latest hypre master from a January 2021 version. I'm calling various solvers using the IJ interface from fortran. For the longest time (several years), I indexed my cells starting at 1 (i.e., 1 to N) for a problem of size N for all my interactions with HYPRE, without any problem. It seems that the new version doesn't like that: I get an error that says `Index out of range! -- hypre_ParVectorGetValues`. I went into par_vector.c and printed out the index value that triggers the problem, and I found that my max index (equal to N) that is larger than HYPRE's expected max of N-1. I see that there were significant changes to memory handling/safety made on Feb 9th, so I'm assuming that along the way the support for a user-specified starting index was dropped, voluntarily or not.
It's not an enormous deal as I can simply start counting at 0 (which indeed fixes the issue), but I thought I should point it out here.

**Comment by rfalgout** [comment]
Hi @desjardi .  One-based indexing should be supported, so we will look into this and get back to you.  Thanks!

**Comment by t34ma** [comment]
I see the same problem, because I also use FORTRAN index starting from 1 and  HYPRE_IJMatrix interface.
In my case where the hypre-2.21.0 is installed to our structural FEM program,  I have an error code like this:

MPI HYPRE(-DHYPRE_WITH_MPI=ON, np=4)
 HYPRE SETUP ERROR CODE=          29
 HYPRE SETUP ERROR CODE=          29
 HYPRE SETUP ERROR CODE=          29
 HYPRE SETUP ERROR CODE=          29

Sequential HYPRE(-DHYPRE_WITH_MPI=OFF)
 HYPRE SETUP ERROR CODE=          29
Index out of range! -- hypre_ParVectorGetValues

 I hope this information would be helpful for your debug.

Regards,
Tetsuya Mishima

**Comment by rfalgout** [comment]
Hi @t34ma and @desjardi .  We are hoping to have a fix for the 1-based indexing issue soon.  Thanks for letting us know!
