### ISSUE TITLE
Accessing entries of a hypreCSR matrix

### ISSUE THREAD

**Issue by psocratis** [hypre-space/hypre#47]
Dear Hypre team, 

I have the following question. 

Given a HypreCSR matrix A, is there an easy way to read a particular entry A(i,j), where i and j are global indices. 
This is assuming that only the processor that "owns" index i will read the entry. 

Thanks, 

Socratis

**Comment by ulrikeyang** [comment]
Hi Socratis,
If it is an IJMatrix you can use HYPRE_IJMatrixGetValues.
On what level are you trying to do this?
Thanks
Ulrike

**Comment by psocratis** [comment]
Hi Ulrike,

Thanks for your response. It's an MFEM hypreParMatrix class resulting from an FEM discretization (really a hypreParCSRMatrix struct).
I basically need to extract part of a row given a list of column indices. I was able to do it using the col_map_offd but I had to include some searches which ideally I would like to avoid.

Is there a conversion from hypreParCSRMatrix to hypre_IJMatrix?

Thanks,

Socratis

________________________________

**Comment by oseikuffuor1** [comment]
Hi Socratis, 
Unfortunately, there is no conversion from hypre_ParCSR to IJMatrix. The IJ_matrix actually holds a ParCSR object, so "conversion" between the two would require a copy. Also, in general, the off-diagonal part of the ParCSR matrix (and I believe the diagonal part as well) is not sorted, so indeed finding the column indexes would require some searching. If your matrix was assembled in a "sorted" way by passing in the complete row entries into hypre (sorted by column indexes), then extracting an entry from the diagonal part of the matrix can be fairly straightforward using the extents of the row partition (ilower, iupper, etc). However, getting an offdiagonal entry would still require some search over the col_map_offd, since the offdiagonal entries have been 'compressed" together.

Thanks, 

-Daniel



  
                                                             
 Daniel Osei-Kuffuor
 Center for Applied Scientific Computing
 Lawrence Livermore National Laboratory
 Livermore, CA 94550
 Mail Code: L-561
 Phone: 925-422-7683
 Email: oseikuffuor1@llnl.gov

**Comment by psocratis** [comment]
Hi Daniel,

Thanks for the response. My situation is exactly as you described. I can get the values of the diag part part easily, but for the offdiag part I do some searching.
It's probably not too bad cause the entries I need are listed in a sorted array and a loop through the whole row from the offdiag part and a search through the sorted array would suffice.
I guess the alternative would be to construct the inverse of the col_offd_map, which will require one pass through all the global indices but more storage on each rank.

Thanks again,

Socratis
________________________________
