### ISSUE TITLE
New hypre_IntArray feature breaks MFEM

### ISSUE THREAD

**Issue by rfalgout** [hypre-space/hypre#479]
See https://github.com/mfem/mfem/issues/2551.  @waynemitchell, can you take a look?  Consider asking @victorapm to help out, since he has recent experience working with the MFEM team and code.  Let me know.  Thanks!

**Comment by waynemitchell** [comment]
@rfalgout Thanks for the heads up. I will take a look at this next week.

**Comment by victorapm** [comment]
Hi all, I looked at this and came up with a fix. The PR for MFEM is https://github.com/mfem/mfem/pull/2553. Could you take a look @waynemitchell? 

As I mentioned there, it's a temporary fix since I use `#ifdef hypre_IntArrayData` to change behavior from the old code (without `hypre_IntArray`) to the new one (current `hypre-master`). It believe it is preferable to use the new `HYPRE_DEVELOP` variables instead.

One last detail: in the same function, MFEM calls 

1.`hypre_BoomerAMGCoarseParms` that uses a CF_marker of type `hypre_IntArray`
2.`hypre_ParCSRMatrixExtractSubmatrixFC` that uses a CF_marker of type `HYPRE_Int *`.

Shouldn't both of them be `hypre_IntArray`?

Thanks!

**Comment by waynemitchell** [comment]
@victorapm Your fixes look good to me. I found one additional issue with the DofFunc: they allocate this on the host, but we have switched this to live on the device. I'll push a change to your mfem branch. Otherwise, I don't see any other issues. Thanks!

**Comment by waynemitchell** [comment]
@victorapm As for your question, not every usage of `HYPRE_Int *` has been replaced with `hypre_IntArray *`. In the case of `hypre_ParCSRMatrixExtractSubmatrixFC`, it is still using `HYPRE_Int *`.

**Comment by victorapm** [comment]
Thanks @waynemitchell! I guess there will be a phased transition to hypre_IntArray once more functions become GPU enabled, right? I just wanted to understand this better :) Thanks!

**Comment by waynemitchell** [comment]
@victorapm It's really only necessary to pass hypre_IntArray as an argument to a function instead of HYPRE_Int* when you require the extra info present in hypre_IntArray, i.e. memory location and/or size. At least this was my criteria for now so that I did not need to go through all of hypre and replace every HYPRE_Int* ... which would have been quite the ordeal. But you are also more or less correct: if `hypre_ParCSRMatrixExtractSubmatrixFC` is ported to the device in the future, it may be necessary to pass hypre_IntArray instead of HYPRE_Int* to make sure that when we call the host/device implementation, the CF_marker actually resides on the host/device.

**Comment by rfalgout** [comment]
Just to throw in my 2 cents, I think we should only use hypre_IntArray as needed for now.  Thanks @victorapm and @waynemitchell!

**Comment by liruipeng** [comment]
It is fine for `hypre_ParCSRMatrixExtractSubmatrixFC` and the the device version to take `int *`, since the memory location is clear from the context. Thanks @victorapm and @waynemitchell

**Comment by victorapm** [comment]
Hi all, the problem in MFEM has been solved and I'm closing this issue. Thanks!
