### ISSUE TITLE
question about ex1 and ex11 in example folder

### ISSUE THREAD

**Issue by zzcsiu** [hypre-space/hypre#545]
I have compiled the code successfully. But I have some problem with ex1 and ex11
for ex1, the screen always shows "<C*b,b>: 0.000000+00", and then the program is over.  i have no any idea what happened. could you please give me some suggestion?

For ex11, I also meet "CUDA ERROR with CODE 0". after I compared with ex5, which is similar with ex11, I found "nnz and i" (in line 227, HYPRE_IJMatrixSetValues(A, 1 &nnz, &i, cols, valuse) ) is wrong. you need to malloc a memory for them like ex5.

thanks.

**Comment by liruipeng** [comment]
Hi @zzcsiu Since the examples use CUDA UVM, there's CPU-GPU race condition (in non-debug mode of hypre). You can run with `CUDA_LAUNCH_BLOCKING=1`, or without it in the debug mode of hypre (configure with `--enable-debug`). Note that this problem only exists in the examples, which we try to keep as simple as possible.

```
li50@lassen555:~/workspace/hypre/master/src/examples$ CUDA_LAUNCH_BLOCKING=1 mpirun -n 2 ./ex1
<C*b,b>: 1.800000e+01


Iters       ||r||_C     conv.rate  ||r||_C/||b||_C
-----    ------------    ---------  ------------ 
    1    2.509980e+00    0.591608    5.916080e-01
    2    9.888265e-01    0.393958    2.330686e-01
    3    4.572262e-01    0.462393    1.077693e-01
    4    1.706474e-01    0.373223    4.022197e-02
    5    7.473022e-02    0.437922    1.761408e-02
    6    3.402624e-02    0.455321    8.020061e-03
    7    1.214929e-02    0.357057    2.863616e-03
    8    3.533113e-03    0.290808    8.327628e-04
    9    1.343893e-03    0.380371    3.167586e-04
   10    2.968745e-04    0.220906    6.997400e-05
   11    5.329671e-05    0.179526    1.256215e-05
   12    7.308483e-06    0.137128    1.722626e-06
   13    7.411552e-07    0.101410    1.746920e-07
```

For ex11, you are right. We need to fix that line. But there are some other problems in this example, so we are not testing it currently. Thank you for reporting it.

**Comment by zzcsiu** [comment]
@liruipeng  thanks a lot for your fast response.
