### ISSUE TITLE
HYPRE_BoomerAMGSetDofFunc arguments and tests

### ISSUE THREAD

**Issue by Raul-Ciria-Aylagas** [hypre-space/hypre#618]
Hi,

I'm using the systems version of BoomerAMG with a system that has different number of dofs and ordering per variable/function.
As far as I understood from the documentation, I can use HYPRE_BoomerAMGSetNumFunctions and HYPRE_BoomerAMGSetDofFunc to tell HYPRE which dofs belongs to each function. Am I right?
I'm trying to implement an extension for PETSc in order to access the hypre function BoomerAMGSetDofFunc from PETSc objects.
I already have an index set (IS) in PETSc with the mapping of each dof (i.e. (0,0,0,...1,1,...k,k) for k>1 ).
From the documentation I see that by default hypre uses a vector of integers (0,1,2,..k,...0,1,2,...k) for k > 1.
How can I test that the hypre preconditioner I'm building has the ordering that I have specified? I suspect that hypre is not saving the mapping i provide.
I'm using the following code to construct the vector:

```
  const PetscInt      *cons_dof_func;
  ISGetIndices(b, &cons_dof_func);
  HYPRE_Int *h_mapping = cons_dof_func; 
  PetscStackCallStandard(HYPRE_BoomerAMGSetDofFunc,jac->hsolver,h_mapping);
```

I would like to know if the argument I'm using for the dof mapping is correctly passed to hypre. 
Additionally, should I free the pointer h_mapping after passing it to Hypre? Or is Hypre handling this automatically?

**Comment by victorapm** [comment]
Hi @Raul-Ciria-Aylagas,

Please see the responses below:

>  I can use HYPRE_BoomerAMGSetNumFunctions and HYPRE_BoomerAMGSetDofFunc to tell HYPRE which dofs belongs to each function. Am I right?

Yes, that's correct.
> How can I test that the hypre preconditioner I'm building has the ordering that I have specified?

I would try a debugger to inspect the value of `dof_func->data`. `dof_func` holds the dof mapping and it is a member of the struct `hypre_ParAMGData`. You can access it through the object that holds the AMG preconditioner. Another way is to add code on `BoomerAMGSetup` for printing that data.

 > Should I free the pointer h_mapping after passing it to Hypre? Or is Hypre handling this automatically?

Hypre takes ownership of the `h_mapping` pointer, and it will be freed at `HYPRE_BoomerAMGDestroy`, so you shouldn't free it. Moreover, I recommend making a memcpy of `cons_dof_func` into `h_mapping`, so that hypre does not free data generated by PETSc's data structures.

Hope this helps!
Victor

**Comment by victorapm** [comment]
I'm closing this issue. Let me know if there are any questions. Thanks!

**Comment by Raul-Ciria-Aylagas** [comment]
Hi @victorapm 

I think we should reopen this issue.
I've been testing the function but I think that there is something wrong with it or the way I access the properties.
After calling `HYPRE_BoomerAMGSetDofFunc` i've tried to get back the data loaded using the following commands:

```
PC_HYPRE       *jac = (PC_HYPRE*)pc->data;
dof_data = hypre_IntArrayData(hypre_ParAMGDataDofFunc((hypre_ParAMGData*) (jac->hsolver)));
dof_size = hypre_IntArraySize(hypre_ParAMGDataDofFunc((hypre_ParAMGData*) (jac->hsolver)));
```

But it returns a size of -1, which I think it means that is has not saved the data. 
Do you know why could this happen and how can I solve this issue?


Thanks
