### ISSUE TITLE
Reduced Precision Usage in AMG coarse layer evaluation

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#705]
Hi All,
Are there any existing Hypre solvers that use reduced precision in the coarse layer evaluation? Are there any plans to do something along these lines? What would be a more significant issue: loss of accuracy or loss of range?
Thanks,
-Paul

**Comment by victorapm** [comment]
Hi Paul, @oseikuffuor1 can comment on this

**Comment by ulrikeyang** [comment]
To answer Paul’s question. There are none at this point. We are working to include such, but this is still a bit far off. Depending on the application loss of accuracy would be a problem. What do you mean by loss of range?

From: PaulMullowney ***@***.***>
Sent: Monday, August 1, 2022 9:30 AM
To: hypre-space/hypre ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [hypre-space/hypre] Reduced Precision Usage in AMG coarse layer evaluation (Issue #705)


Hi All,
Are there any existing Hypre solvers that use reduced precision in the coarse layer evaluation? Are there any plans to do something along these lines? What would be a more significant issue: loss of accuracy or loss of range?
Thanks,
-Paul

**Comment by PaulMullowney** [comment]
By loss of range, I mean that an AMG layer may produce an output that exceeds the min/max of the precision used. Imagine an extreme case of trying to evaluate a layer with FP16.

For Deep Neural Nets, dynamic range can be a significant issue for low precision training especially if you don't build the layers with right kinds of normalization. One often sees the intermediate layers that produce outputs that rapidly exceed precision limits.

I was wondering if AMG would face similar issues?

**Comment by oseikuffuor1** [comment]
To add to Ulrike's comment, yes the main issue would be loss of accuracy due to roundoff error. When used as a preconditioner, this may be less of an issue however. The dynamic range issue would depend on the problem. AMG would encounter issues if the coarse problem is outside the dynamic range of the precision on the coarse level. There's not much you can do about that but to use a format with more precision, BFloats, or storing in higher precision while computing in lower precision, among other strategies.

-Daniel




Daniel Osei-Kuffuor

Center for Applied Scientific Computing

Lawrence Livermore National Laboratory

Livermore, CA 94550

Mail Code: L-561

Phone: 925-422-7683

Email: ***@***.******@***.***>

________________________________

**Comment by PaulMullowney** [comment]
Thanks for the input.
