### ISSUE TITLE
ForceSyncComputeStream and GPU-aware MPI

### ISSUE THREAD

**Issue by PaulMullowney** [hypre-space/hypre#713]
Why is hypre_ForceSyncComputeStream necessary when using GPU-aware MPI? Alternatively, why isn't hypre_SyncComputeStream sufficient?

-Paul

**Comment by liruipeng** [comment]
Hi @PaulMullowney, GPU-aware MPI doesn't seem to wait for running kernels to finish. So, we have to force sync before calling MPI. On the other hand, normal MPI from host doesn't need this synchronization because cudaMemcpy is blocking.

The reason we can't use `hypre_SyncComputeStream` is that we have the logic that without UVM being enabled it actually does nothing. This logic makes sense since CPU cannot touch GPU device memory so no race condition can happen and inside hypre we don't have more than 1 stream. However, with GPU-aware MPI, we need to sync anyways.

Hope this can help!

Thanks

**Comment by PaulMullowney** [comment]
Ok. I see the same thing on crusher. GPU-aware MPI doesn't see to wait for kernel completion.
