### ISSUE TITLE
Hypre segfault when calling hypre_DeviceDataStream when using SYCL

### ISSUE THREAD

**Issue by ARSanderson** [hypre-space/hypre#832]
When using Hypre with SYCL 

If one calls : HYPRE_Finalize()

before calling: hypre_PCGDestroy (or similar)

https://github.com/hypre-space/hypre/blob/832ad94de321b583424a958b4659a7bbe7204676/src/utilities/device_utils.c#L415

the sycl_device will be invalid and result in a seg fault down stream.

The issue manifests itself when one relies on reference counted pointers to hold Hypre structures which may be released data AFTER HYPRE_Finalize() is called.

Fix: An assert should be called that catches that the sycl device is invalid (nullptr) due more than likely because HYPRE_Init() has not been called or HYPRE_Finalize() has already been called.

This error does not manifest itself with CUDA or HIP only with SYCL.

**Comment by waynemitchell** [comment]
I want to clarify your use case a bit here. In general, I would not recommend calling any hypre functionality after calling HYPRE_Finalize(). Do you have a reason that you are purposefully trying to destroy hypre objects after calling HYPRE_Finalize()? Or are you just concerned with how the error is handled, i.e. you would prefer a failed assert to a seg fault?

This kind of thing will only happen with sycl (not cuda/hip) because sycl explicitly keeps track of devices and queues in a way that has no analogue in cuda/hip. So there are some extra objects stored as part of the hypre handle that get destroyed when you call finalize that are macro'd out when configured for cuda/hip.

**Comment by ARSanderson** [comment]
There should be an assert with some details so to give the user some guidance. Letting it seg fault does not help the user. That is the user was calling hypre functionality before/after HYPRE_Init()/HYPRE_Finalize() had been called. Something to that affect should be enough of a clue. 

Such a message would have helped greatly in the case I found where the code was indirectly (and unbeknown to me) calling a hypre destroy function because a reference counted pointer still had a hypre object when HYPRE_Finalize() was called. The code worked with CUDA/HIP with no ill affect so those who wrote that code thought it was good. I moved to SYCL and got the seg fault.

It took some time to figure out the issue which was actually in two places. The first, took some effort to find. Once fixed I hit got another seg fault and immediately knew the issue.

**Comment by waynemitchell** [comment]
OK, thanks for the context. This is helpful. I'll look at implementing a fix. I just wanted to verify that there wasn't some reason you needed to do memory operations after HYRPE_Finalize(), which would be much more difficult to accommodate. Getting some better error catching messages implemented should be doable.

**Comment by ARSanderson** [comment]
Thanks ... should be an easy assert to trap as the device pointer is null. At least was in the cases I hit.

**Comment by ARSanderson** [comment]
Thanks for the addition.
