### ISSUE TITLE
Example for zeroing structure boundaries does not match the initialization.

### ISSUE THREAD

**Issue by kellerdek** [hypre-space/hypre#841]
The example being used as described by the prvious sections only seems to have a south boundary of 3 values for process zero.
Yet they are zeroing 12 values?  And the ilower and iupper are set for 6 values across values ‘owned’ by two different processes.

int  ilower[2] = {-3, 1};
int  iupper[2] = { 2, 1};

/* create matrix and set interior coefficients */
...

/* implement boundary conditions */
...

for (i = 0; i < 12; i++)
{
   values[i] =  0.0;
}

i = 3;
HYPRE_StructMatrixSetBoxValues(A, ilower, iupper, 1, &i, values);

/* complete implementation of boundary conditions */
...

**Comment by rfalgout** [comment]
Hi @kellerdek .  I assume you are looking at the documentation and not `examples/ex1.c` (they are related but not the same).  If so, then the 12 should be a 6 (both boxes are owned by process 0).  This code will still work just fine as written, but it's confusing and we will fix it.  This mistake dates back to at least the year 2000, it turns out.  The best excuse I can come up with is that maybe the very first version of this had Neumann boundary conditions and adjusted both the center and south coefficients at the same time, then it was modified to Dirichlet and we forgot to change the 12 to a 6.  It's just a theory though.  Thanks!

**Comment by kellerdek** [comment]
Very good.  Thanks!  I have been struggling with some inconsistencies and had gone back to the documentation.
