### ISSUE TITLE
HYPRE_ParCSRMatrixGetDims() returned 256

### ISSUE THREAD

**Issue by geyan3566** [hypre-space/hypre#94]
Hi, 

I'm solving a nonlinear problem in `mfem`, in which the `hypre` GMRES solver with EUCLID preconditioner is used in the newton solver. I got the desired results when there are around 1000 degrees of freedom. However, I got the following error message after the first newton iteration as I increase the number of dofs.
```
Newton iteration  1 : ||r|| = 0.000551856, ||r||/||r_0|| = 0.0156795
============= error stack trace ====================
[0] ERROR: HYPRE_ParCSRMatrixGetDims() returned 256
       EuclidGetDimensions (HYPRE)  file= getRow_dh.c  line= 66

[0] called from: Euclid_dhSetup  file= Euclid_dh.c  line= 173
[0] called from: HYPRE_EuclidSetup  file= HYPRE_parcsr_Euclid.c  line= 278

application called MPI_Abort(MPI_COMM_WORLD, -1) - process 0
```

To reproduce this error, please refer to [https://github.com/mfem/mfem/issues/1308](url).

Thank you,
Ge

**Comment by oseikuffuor1** [comment]
Hi Ge, 
Are you doing a fixed number of GMRES iterations or are you converging the linear solve before updating the Newton iteration? If you are using both stopping criteria for GMRES (tol and max. number of iterations), then can you confirm that the linear solver converges for the first Newton step? 
-Daniel

**Comment by geyan3566** [comment]
Hi Daniel,

Thanks for replying to this question.
I'm trying to converge the linear solver before updating the newton iteration.
Your suspension is right, as I increase the number of dofs, the linear solver failed to converge with max iteration = 100 and tol = 1e-13.
Here is the output:
```
GMRES Iterations = 100
Final GMRES Relative Residual Norm = 2.79381e-11
Newton iteration  2 : ||r|| = 9.72065e-10, ||r||/||r_0|| = 5.3917e-07
Time for calc gradient: 0.204757.
Time for set A matrix: 0.000299454.

============= error stack trace ====================
[0] ERROR: HYPRE_ParCSRMatrixGetDims() returned 256
       EuclidGetDimensions (HYPRE)  file= getRow_dh.c  line= 66

[0] called from: Euclid_dhSetup  file= Euclid_dh.c  line= 173


```
After I change the ilu preconditioner fill level, it works. 

Thanks,
Ge

**Comment by oseikuffuor1** [comment]
Hi Ge, 
So the error you are seeing is because hypre sets an error flag that the solver did not converge after the first solve. But the preconditioner checks to see if all errors are clear before constructing the new one. If the error flag is set, then it will fail to setup the preconditioner. There are a few ways to get around this. The easiest way is to use the max iteration parameter to determine convergence and set tol = 0. This way, hypre will not set the flag once the max iterations is reached. Another alternative is to clear the error flag after each Newton iteration, by calling HYPRE_Int HYPRE_ClearAllErrors(); This will reset the error flag for the next iteration. A third option is what you are doing now. That is, use a higher fill level to construct a better preconditioner that is able to meet the tolerance-based stopping criteria. However, since you are setting the tolerance to be so small, you might as well use the first option and set tol = 0. with max iterations = 100.

Hope this helps.
-Daniel
